import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/contexts/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // "other" es el escape hatch de la Metadata API de Next para metas
  // arbitrarios que no tienen un campo dedicado (como "description" o
  // "openGraph"). Esto renderiza <meta name="google" content="notranslate" />
  // en el <head>, que es la señal que Google Translate / el traductor
  // integrado de Chrome respeta para NO ofrecer ni forzar la traducción
  // de la página.
  other: {
    google: "notranslate",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // lang="es": la página es en español, así que el traductor ya no
    // tiene un "idioma detectado ≠ idioma declarado" que lo dispare
    // automáticamente. translate="no" es el atributo estándar (soportado
    // por Chrome y Google Translate) que le dice explícitamente al
    // traductor que no toque el DOM de esta página. Ambos + el meta tag
    // de arriba son necesarios en conjunto: cada uno cubre un mecanismo
    // distinto (heurística de idioma, atributo por elemento, y meta a
    // nivel de documento) por el que el traductor se pudo haber
    // activado en Chrome Android.
    <html
      lang="es"
      translate="no"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}